name: Build & Deploy

on:
  push:
    branches: [ feat/actions ]
  pull_request:
    branches: [ feat/actions ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup meteor
      uses: meteorengineer/setup-meteor@v1.0.3
    - name: Meteor install
      run: meteor npm install
      working-directory: ./bigbluebutton-html5
    - name: Buid
      run: meteor build --server-only ./meteorbundle
      working-directory: ./bigbluebutton-html5
    - uses: actions/upload-artifact@v2
      with:
        name: result
        path: bigbluebutton-html5/meteorbundle/bigbluebutton-html5.tar.gz
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: result
    - name: Setup SSH Keys and known_hosts
      run: |
        ssh-agent -a /tmp/ssh_agent.sock > /dev/null
        eval "$(ssh-agent)"
        ssh-add - <<< "${{ secrets.KEY }}"
    - name: Deploy
      run: |
        scp bigbluebutton-html5.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'echo ${{ secrets.PASS }} | sudo -S tar -zxf ~/bigbluebutton-html5.tar.gz -C /usr/share/meteor && rm -f ~/bigbluebutton-html5.tar.gz'
