name: Build & Deploy

on:
  push:
    branches: [ feat/actions ]
  pull_request:
    branches: [ feat/actions ]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        meteor: [2.5.3]

    steps:
    - uses: actions/checkout@v2
    - name: Setup meteor
      uses: meteorengineer/setup-meteor@v1.0.3
      with:
          meteor-release: ${{ matrix.meteor }}
    - name: Meteor install
      run: meteor npm install
      working-directory: ./bigbluebutton-html5
    - name: Buid
      run: meteor build --server-only ./meteorbundle
      working-directory: ./bigbluebutton-html5
    - uses: actions/upload-artifact@v2.3.1
      with:
        name: result
        path: bigbluebutton-html5/meteorbundle/*.tar.gz
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2.1.0
      with:
        name: result
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "*.tar.gz"
        target: "/usr/share/meteor"
